### PR TITLE
Ocaid finder

### PR DESCRIPTION
**Pull request by xayhewalo**
Provides a dump of malformed  editions to close https://github.com/internetarchive/openlibrary/issues/2651

## Description:
In this Pull Request we have made the following changes:
* Adds a script to make a tsv of editions with Internet Archives scans but no `ocaid`

### CODE REVIEW

**Comment by tfmorris** [comment]
Hmmm, my 1-liner above, which took 20 minutes to run against the complete dump, generated a total of 50464 candidates, which is much higher than your quoted "25908 missing ocaids." I suspect perhaps you're getting 5xx or some other error from your API calls.

**Comment by guyjeangilles** [comment]
@tfmorris I plan on implementing the feedback you provided this weekend. I'll report back with results

**Comment by guyjeangilles** [comment]
On the 2020-02-29 dump I'm finding 58520 editions. The exact commands are below.

This suggests that between January and February, ~8k editions were scanned with incomplete metadata. I'm 

```bash
$ pv ~/Downloads/ol_dump_editions_2020-02-29.txt.gz | zgrep -v '"ocaid":' | zgrep -E '("ia_loaded_id|"ia:)' | gzip > no_ocaids.tsv.gz
5.66GiB 0:06:46 [14.3MiB/s] [====================================================================================================================================>] 100
$ wc -l no_ocaids.tsv.gz 
58520 no_ocaids.tsv.gz


```

**Comment by mekarpeles** [comment]
@xayhewalo anything I may do to help unblock you on this PR?

**Comment by xayhewalo** [comment]
@mekarpeles , I've been working on another project, but if I recall correctly, I just needed a bot account to change ocaid so this script needs to be rewritten. Nothing is blocking

**Pull request closed without merging**
